ARRAY OPERATIONS

In [1]:
import numpy as np

Arithmetic Operations

In [6]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [9]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [12]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [14]:
arr1 = np.array([1,2,3,4,5])  #adding a certain value to every element of the array
arr1 + 10

array([11, 12, 13, 14, 15])

In [18]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [20]:
arr2 *2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow Copy

In [22]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [27]:
a     #Shallow Copy(happens when sliced because it takes up another location.)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
b = a   #DEEP COPY
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a  # a got changed by changing the value in b because a was assigned in b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
c = np.arange(1,21)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
d = c.copy()  #Shallow Copy
d[0] = 99
d

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [40]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [44]:
A @ B   # @ is used to do matrix multiplication

array([[19, 22],
       [43, 50]])

In [45]:
np.dot(A,B)  #Second method to do matrix multiplication

array([[19, 22],
       [43, 50]])

In [47]:
A

array([[1, 2],
       [3, 4]])

In [46]:
A.T   #Transpose of a matrix

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

Stacking Array

In [54]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [55]:
np.vstack((a,b))  #VERTICAL STACK

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
np.hstack((a,b))   #HORIZONTAL STACK

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
np.column_stack((a,b))   #COLUMN STACK

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Arrays

In [58]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.hsplit(c,2)   #Horizontal Split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
np.vsplit(c,4)   #Vertical Split

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]