In [19]:
import numpy as np

BASIC ARRAY CREATION

In [21]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [22]:
a = [1,2,3.5,"hello",5]
a     #This is a list and hence multiple datatype is supported.

[1, 2, 3.5, 'hello', 5]

In [23]:
np.array(a)     #converted list into array where the datatypes are converted into string

array(['1', '2', '3.5', 'hello', '5'], dtype='<U32')

In [24]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l      #Lists doesn't support multi dimensions. It only supports vectors

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
np.array(l)   #Arrays support multi dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GENERATION FUNCTION

In [28]:
arr = np.arange(1,11,2)  #Creates an array (start, stop-1, step)
arr

array([1, 3, 5, 7, 9])

In [32]:
arr = np.zeros((6,6))
arr      #Matrix of Zeroes

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
arr = np.ones((4,8))
arr      #Matrix of Ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
arr = np.linspace(1,10,20)   
#linspace means linear space (start, end, no. of linear parts). when given a range, it splits the range linearly into the
#no of parts that are being given.
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

RANDOM GENERATION FUNCTION   (random lib is called with numpy)

In [38]:
np.random.rand(10)  #Normalization where random number is printed between -1 and 1

array([0.03705117, 0.80886312, 0.13290554, 0.53970325, 0.15479837,
       0.84641368, 0.5966013 , 0.01261524, 0.13925214, 0.4733695 ])

In [37]:
np.random.randn(10)  #Standardization where random number is printed between -3 and 3

array([ 0.37751713,  1.73331074, -0.20779757, -1.05396032,  0.64437085,
        0.22429582,  0.64255921, -0.77692875, -0.37023503, -0.60525264])

In [40]:
np.random.randint(10,20,5) #random integers (start, stop, no. of integers)

array([18, 17, 13, 14, 17])

ARRAY ATTRIBUTES

In [58]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [59]:
arr.shape

(3, 3)

In [60]:
arr.size

9

In [69]:
print(arr.dtype)

int64


In [70]:
#ARRAY METHODS

In [71]:
print(arr.min())

1


In [72]:
print(arr.max())

9


In [73]:
print(arr.sum())

45


In [74]:
np.sum(arr, axis = 0)  #axis = 0 for row sum, axis = 1 for column sum

array([12, 15, 18])

In [75]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [68]:
arr.mean()

np.float64(5.0)

In [76]:
arr.std()   #Standard Deviation

np.float64(2.581988897471611)

In [77]:
arr.argmax() #argument max -> max value element's index

np.int64(8)

In [78]:
arr.argmin() #argument min -> min value element's index

np.int64(0)

RESIZING AND RESHAPING

In [79]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [82]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])