In [2]:
import numpy as np

NUMPY SLICING AND INDEXING OF VECTORS

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr_slice = arr[1:7:2]  #Slicing [start:stop+1:step]
arr_slice

array([12, 14, 16])

NUMPY SLICING AND INDEXING OF MATRIX

In [14]:
arr = np.arange(1,31).reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[5]  #Prints the row of index 5
print(arr[0,0])   #Prints the first element [row index, column index]

1


In [20]:
slice = arr[0:2,1:3]  #Slices matrix [row_index_start: row_index_stop+1, column_index_start, column_index_stop+1]
slice

array([[2, 3],
       [7, 8]])

In [23]:
slice2 = arr[3:,3:]  #not giving stop means it goes till the end
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [25]:
slice3 = arr[0:,0:1]  #Column Slicing
slice3

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]])

BOOLEAN INDEXING

In [26]:
#finding even numbers
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr%2 == 0   #even number checking
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [29]:
arr[bool_index]

array([12, 14, 16, 18, 20])