In [2]:
import numpy as np

VALID SUDOKU

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [9]:
b = np.sum(s, axis = 1)
for i in b:
    if i != 45:
        print("Sudoku is not valid.")
        break
else:
    print("Sudoku is valid for rows.")

Sudoku is valid for rows.


In [12]:
c = np.sum(s, axis = 0)
for i in c:
    if i != 45:
        print("Sudoku is not valid.")
        break
else:
    print("Sudoku is valid for columns.")

Sudoku is valid for columns.


In [16]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


GENERAL QUESTIONS

In [59]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [60]:
#Get the shape of the matrix.

In [61]:
data.shape

(5, 3)

In [62]:
#Find the average age of students.

In [63]:
col = data[:,0]
print(f"Average age is {col.mean()}.")

Average age is 18.4.


In [64]:
#Extract Math marks of all students.

In [65]:
data[:,1]

array([85, 92, 76, 65, 90])

In [66]:
#Find the highest Science mark.

In [67]:
scimark = data[:,2]
print(f"Max Science marks is {scimark.max()}.")

Max Science marks is 95.


In [68]:
#Get details of the student who scored more than 90 in Math.

In [69]:
mathmark = data[:,1]
mathmark
count = 0
for i in mathmark:
    if i>90:
        count +=1
print(count)

1


In [70]:
#Increase Math marks of all students by 5.

In [71]:
mathmark = data[:,1]
updmarks = mathmark + 5
for i in updmarks:
    print(i)

90
97
81
70
95


In [72]:
#Find how many students are younger than 19.

In [73]:
age = data[:,1]
age
count = 0
for i in age:
    if i>19:
        count +=1
print(count)

5


In [74]:
#Calculate the average marks in each subject (column-wise mean).

In [75]:
col1 = data[:,1]
print(f"Average Math marks is {col1.mean()}.")

Average Math marks is 81.6.


In [76]:
col2 = data[:,2]
print(f"Average Science marks is {col2.mean()}")

Average Science marks is 83.2


In [77]:
#Get data of students who scored at least 80 in both subjects.

In [78]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]           

array([[19, 92, 88],
       [20, 90, 85]])

In [79]:
#Replace all Science marks < 75 with 0.

In [80]:
data[:,2][data[:,2] < 75] = 0        
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])